IF (QTHYBRID_INCLUDE_DIR AND QTHYBRID_LIBRARIES)
  # in cache already
  SET(QTHYBRID_FOUND TRUE)

ELSE (QTHYBRID_INCLUDE_DIR AND QTHYBRID_LIBRARIES)

  IF(NOT QTHYBRID_FIND_COMPONENTS)
    # default
    SET(QTHYBRID_FIND_REQUIRED_COMPONENTS FRWK HTMAPP)
   
  ENDIF(NOT QTHYBRID_FIND_COMPONENTS)

  FIND_PATH(QTHYBRID_INCLUDE_DIR htmapp.h)
  FIND_LIBRARY(QTHYBRID_FRWK_LIBRARY NAMES QThybridfrwk  HINTS "${QTHYBRID_INCLUDE_DIR}/../../lib")
  FIND_LIBRARY(QTHYBRID_HTMAPP_LIBRARY NAMES QThybridhtmapp   HINTS "${QTHYBRID_INCLUDE_DIR}/../../lib")

  SET(QTHYBRID_FOUND ON)

  FOREACH(NAME ${QTHYBRID_FIND_REQUIRED_COMPONENTS})
        # only good if header and library both found   
        IF( QTHYBRID_${NAME}_LIBRARY)
            LIST(APPEND QTHYBRID_LIBRARIES    ${QTHYBRID_${NAME}_LIBRARY})
        ELSE( QTHYBRID_${NAME}_LIBRARY)
            SET(QTHYBRID_FOUND OFF)
        ENDIF( QTHYBRID_${NAME}_LIBRARY)
    ENDFOREACH(NAME)


MARK_AS_ADVANCED(FORCE
                 QTHYBRID_ROOT_DIR
                 QTHYBRID_INCLUDE_DIRS
                 QTHYBRID_LIBRARIES
                 QTHYBRID_FRWK_LIBRARY
                 QTHYBRID_HTMAPP_LIBRARY
                 )
  
 # display help message
IF(NOT QTHYBRID_FOUND)
    # make FIND_PACKAGE friendly
    IF(QTHYBRID_FIND_REQUIRED)
        MESSAGE(FATAL_ERROR "QTHybrid 1.0 not found. Please specify it's location with the QTHYBRID_ROOT_DIR env. variable.")
    ELSE(QTHYBRID_FIND_REQUIRED)
        MESSAGE(STATUS "QTHybrid 1.0 not found.")
    ENDIF(QTHYBRID_FIND_REQUIRED)
ENDIF(NOT QTHYBRID_FOUND)

ENDIF (QTHYBRID_INCLUDE_DIR AND QTHYBRID_LIBRARIES)


